services:
  - type: web
    name: skillflare-backend
    runtime: node
    buildCommand: yarn install && cd backend && yarn install
    startCommand: cd backend && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://skillflare-delta.vercel.app
